core/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.index, name="index"),
    path('employees/', views.employees, name="employees")
]

lr6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models


class Worker(models.Model):
    name = models.CharField(max_length=40)
    position = models.CharField(max_length=30)
    phone_number = models.CharField(max_length=15)


core/views.py
from django.shortcuts import render
import datetime
import requests
from .models import Worker


def index(request):
    context = {'date': datetime.date.today(),
               'paragraph1': requests.get('https://baconipsum.com/api/?type=all-meat&sentences=5&start-with-lorem=1&format=text').content,
               'paragraph2': requests.get('https://baconipsum.com/api/?type=all-meat&sentences=7&format=text').content}
    return render(request, 'core/index.html', context)


def employees(request):
    return render(request, 'core/employees-list.html')

templates/core/employees-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список Сотрудников</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'core/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
</head>
<body>

  <div id="placeholder">

    <div id="logo">
        <a href="../core/index.html"><img src="{% static 'core/pics/logo.png' %}" alt="Hills logo"></a>
      </div>

    <div id="nav">
        <a>Список сотрудников </a>
        <a href="best-employee-of-the-month.html">Сотрудник месяца </a>
        <a href="add-employee.html">Добавить сотрудника </a>
    </div>
  </div>

  <h1>Список Сотрудников: </h1>

  <div class="table">
    <table>
      <thead>
        <tr>
          <th>Имя и Фамилия</th>
          <th>Должность</th>
          <th>Телефон</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>Валентина Назарова</td>
          <td>Старший сыщик</td>
          <td>+357-25-998877</td>
        </tr>

        <tr>
          <td>Тимофей Назаров</td>
          <td>Младший сыщик</td>
          <td>+7-812-999-11-22</td>
        </tr>

        <tr>
          <td>Кирилл Мухрыгин</td>
          <td>Сотрудник архива</td>
          <td>+7-812-999-22-33</td>
        </tr>

        <tr>
          <td>Марвин Назаров</td>
          <td>Талисман</td>
          <td>+357-25-998877</td>
        </tr>




      </tbody>
    </table>
  </div>

</body>
</html>

templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hills</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'core/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
</head>
<body>
    <div id="placeholder">

      <div id="logo">
        <img src="{% static 'core/pics/logo.png' %}" alt="Hills logo">
      </div>

      <div id="nav">
          <a href="{% url 'core:employees' %}">Список сотрудников </a>
          <a href="html/best-employee-of-the-month.html">Сотрудник месяца </a>
          <a href="htmladd-employee.html">Добавить сотрудника </a>
      </div>
    </div>

    <h1>Детективное агентство "Холмы"</h1>

    <div class="main">
        <p>{{paragraph1}}</p>
        <p>{{paragraph2}}</p>

    </div>

    <div id="footer">
      <h4>640 С Мэйн Стрит, Лос-Анджелес, CA 90014, США, 34°02′39.04″N 118°15′01.97″W</h4>
      <h4>{{ date }}</h4>
    </div>

</body>
</html>